language: node_js
node_js:
  - "8"

branches:
  only:
  - "prototype-v0.1"

before_install:
  - openssl aes-256-cbc -K $encrypted_c3b52e7260fb_key -iv $encrypted_c3b52e7260fb_iv -in private-key.pem.enc -out private-key.pem -d
  - npm install -g serverless
  - sudo apt-get install python3
  - sudo pip install awscli

install:
  - make install

script:
  - echo 'No tests, this is a PROTOTYPE only'

after_success:
  - make deploy
